### ISSUE TITLE
feats.pth

### ISSUE THREAD

**Issue by guoneidaxubh** [iCVTEAM/Gard#2]

**Comment by guoneidaxubh** [comment]
Hello, where was feats.pth generated?

**Comment by zhao1f** [comment]
The [tools/get_vis_result.py](https://github.com/iCVTEAM/Gard/blob/f5f89c5c47e875c871ba0c48f64df9018235484b/tools/get_vis_result.py) is abondoned,  This pth file is not used to run the training and testing code

**Comment by guoneidaxubh** [comment]
> The [tools/get_vis_result.py](https://github.com/iCVTEAM/Gard/blob/f5f89c5c47e875c871ba0c48f64df9018235484b/tools/get_vis_result.py) is abondoned, This pth file is not used to run the training and testing code

Thank u very much！
