### ISSUE TITLE
visualizer problem

### ISSUE THREAD

**Issue by JJJTF** [iCVTEAM/Gard#6]
Excuse me again!

Get in the tools directory_ vis_ Lines 53 and 54 in the result.py file, gallery_ feats = torch.load(Cfg.LOG_DIR + 'feats.pth') and img_ Path=np. load ('./log/imgpath. npy'), but I don't know where 'feats.pth' and './log/imgpath. npy' are. And this code cannot run through either.

I hope you can help me answer, thank you very much!

**Comment by zhao1f** [comment]
Sorry for the late reply, this visualization manuscript is used for other image retrieval tasks (we need to know which images are selected), and for the fine-grained classification task in this paper, ignoring this visualization should be OK.

**Comment by JJJTF** [comment]
Thank you very much for your reply.

I have read your paper 'Graph based High Order Relationship Discovery for Fine grained Recognition' and the code, and I am very interested in your work.

I would like to know how the thermodynamic diagram was drawn in your paper. Because I know that in the graph stage, the image no longer has a rectangular structure, and I don't know how to process it into a thermal diagram, so I would like to ask for your advice.

**Comment by zhao1f** [comment]
The visualization used in the paper is generated by the class activation maps. To be specific, the gradient-CAM [paper link](https://arxiv.org/abs/1610.02391) is used in this paper. If you are a beginner at this problem and do not need to visualize the gradients but only the heat map, I recommended referring to other vanilla implementations of CAMs, including [code link](https://github.com/frgfm/torch-cam).

As mentioned, the graph stage would break its structural information, so we need to visualize the feature maps (e.g., stage 4 for ResNet) but not graph nodes to show where the network is "focusing on".

Hope this can help.
